//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("ProductListDBModel", "FK_Products_Measures", "Measure", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(ProductListDBModel.Measure), "Product", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ProductListDBModel.Product), true)]
[assembly: EdmRelationshipAttribute("ProductListDBModel", "FK_Shopping_List_Clients", "Client", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(ProductListDBModel.Client), "Shopping_List", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ProductListDBModel.Shopping_List), true)]
[assembly: EdmRelationshipAttribute("ProductListDBModel", "FK_Shopping_List_Products", "Product", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(ProductListDBModel.Product), "Shopping_List", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ProductListDBModel.Shopping_List), true)]
[assembly: EdmRelationshipAttribute("ProductListDBModel", "FK_Shopping_List_Hist_Clients", "Client", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ProductListDBModel.Client), "Shopping_List_Hist", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ProductListDBModel.Shopping_List_Hist), true)]
[assembly: EdmRelationshipAttribute("ProductListDBModel", "FK_Shopping_List_Hist_Products", "Product", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ProductListDBModel.Product), "Shopping_List_Hist", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ProductListDBModel.Shopping_List_Hist), true)]
[assembly: EdmRelationshipAttribute("ProductListDBModel", "FK_Tips_Clients", "Client", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(ProductListDBModel.Client), "Tip", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ProductListDBModel.Tip), true)]
[assembly: EdmRelationshipAttribute("ProductListDBModel", "Product_in_storeProduct", "Product_in_store", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ProductListDBModel.Product_in_store), "Product", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(ProductListDBModel.Product), true)]

#endregion

namespace ProductListDBModel
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ProdListDBEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ProdListDBEntities object using the connection string found in the 'ProdListDBEntities' section of the application configuration file.
        /// </summary>
        public ProdListDBEntities() : base("name=ProdListDBEntities", "ProdListDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ProdListDBEntities object.
        /// </summary>
        public ProdListDBEntities(string connectionString) : base(connectionString, "ProdListDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ProdListDBEntities object.
        /// </summary>
        public ProdListDBEntities(EntityConnection connection) : base(connection, "ProdListDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<City> Cities
        {
            get
            {
                if ((_Cities == null))
                {
                    _Cities = base.CreateObjectSet<City>("Cities");
                }
                return _Cities;
            }
        }
        private ObjectSet<City> _Cities;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Client> Clients
        {
            get
            {
                if ((_Clients == null))
                {
                    _Clients = base.CreateObjectSet<Client>("Clients");
                }
                return _Clients;
            }
        }
        private ObjectSet<Client> _Clients;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Measure> Measures
        {
            get
            {
                if ((_Measures == null))
                {
                    _Measures = base.CreateObjectSet<Measure>("Measures");
                }
                return _Measures;
            }
        }
        private ObjectSet<Measure> _Measures;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Product> Products
        {
            get
            {
                if ((_Products == null))
                {
                    _Products = base.CreateObjectSet<Product>("Products");
                }
                return _Products;
            }
        }
        private ObjectSet<Product> _Products;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Shopping_List> Shopping_List
        {
            get
            {
                if ((_Shopping_List == null))
                {
                    _Shopping_List = base.CreateObjectSet<Shopping_List>("Shopping_List");
                }
                return _Shopping_List;
            }
        }
        private ObjectSet<Shopping_List> _Shopping_List;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Shopping_List_Hist> Shopping_List_Hist
        {
            get
            {
                if ((_Shopping_List_Hist == null))
                {
                    _Shopping_List_Hist = base.CreateObjectSet<Shopping_List_Hist>("Shopping_List_Hist");
                }
                return _Shopping_List_Hist;
            }
        }
        private ObjectSet<Shopping_List_Hist> _Shopping_List_Hist;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Tip> Tips
        {
            get
            {
                if ((_Tips == null))
                {
                    _Tips = base.CreateObjectSet<Tip>("Tips");
                }
                return _Tips;
            }
        }
        private ObjectSet<Tip> _Tips;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagram> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagram>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagram> _sysdiagrams;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Product_in_store> Product_in_store
        {
            get
            {
                if ((_Product_in_store == null))
                {
                    _Product_in_store = base.CreateObjectSet<Product_in_store>("Product_in_store");
                }
                return _Product_in_store;
            }
        }
        private ObjectSet<Product_in_store> _Product_in_store;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Sector> Sectors
        {
            get
            {
                if ((_Sectors == null))
                {
                    _Sectors = base.CreateObjectSet<Sector>("Sectors");
                }
                return _Sectors;
            }
        }
        private ObjectSet<Sector> _Sectors;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Store> Stores
        {
            get
            {
                if ((_Stores == null))
                {
                    _Stores = base.CreateObjectSet<Store>("Stores");
                }
                return _Stores;
            }
        }
        private ObjectSet<Store> _Stores;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Cities EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCities(City city)
        {
            base.AddObject("Cities", city);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Clients EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToClients(Client client)
        {
            base.AddObject("Clients", client);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Measures EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMeasures(Measure measure)
        {
            base.AddObject("Measures", measure);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Products EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProducts(Product product)
        {
            base.AddObject("Products", product);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Shopping_List EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToShopping_List(Shopping_List shopping_List)
        {
            base.AddObject("Shopping_List", shopping_List);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Shopping_List_Hist EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToShopping_List_Hist(Shopping_List_Hist shopping_List_Hist)
        {
            base.AddObject("Shopping_List_Hist", shopping_List_Hist);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Tips EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTips(Tip tip)
        {
            base.AddObject("Tips", tip);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagram sysdiagram)
        {
            base.AddObject("sysdiagrams", sysdiagram);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Product_in_store EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProduct_in_store(Product_in_store product_in_store)
        {
            base.AddObject("Product_in_store", product_in_store);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Sectors EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSectors(Sector sector)
        {
            base.AddObject("Sectors", sector);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Stores EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToStores(Store store)
        {
            base.AddObject("Stores", store);
        }

        #endregion

        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="luser">No Metadata Documentation available.</param>
        public ObjectResult<global::System.String> Shopping_list_proc(Nullable<global::System.Int32> luser)
        {
            ObjectParameter luserParameter;
            if (luser.HasValue)
            {
                luserParameter = new ObjectParameter("luser", luser);
            }
            else
            {
                luserParameter = new ObjectParameter("luser", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction<global::System.String>("Shopping_list_proc", luserParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="product_id">No Metadata Documentation available.</param>
        /// <param name="amount">No Metadata Documentation available.</param>
        /// <param name="userid">No Metadata Documentation available.</param>
        public int UpdateProductAmount(Nullable<global::System.Int32> product_id, Nullable<global::System.Double> amount, Nullable<global::System.Int32> userid)
        {
            ObjectParameter product_idParameter;
            if (product_id.HasValue)
            {
                product_idParameter = new ObjectParameter("product_id", product_id);
            }
            else
            {
                product_idParameter = new ObjectParameter("product_id", typeof(global::System.Int32));
            }
    
            ObjectParameter amountParameter;
            if (amount.HasValue)
            {
                amountParameter = new ObjectParameter("amount", amount);
            }
            else
            {
                amountParameter = new ObjectParameter("amount", typeof(global::System.Double));
            }
    
            ObjectParameter useridParameter;
            if (userid.HasValue)
            {
                useridParameter = new ObjectParameter("userid", userid);
            }
            else
            {
                useridParameter = new ObjectParameter("userid", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction("UpdateProductAmount", product_idParameter, amountParameter, useridParameter);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ProductListDBModel", Name="City")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class City : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new City object.
        /// </summary>
        /// <param name="city_id">Initial value of the city_id property.</param>
        public static City CreateCity(global::System.Int32 city_id)
        {
            City city = new City();
            city.city_id = city_id;
            return city;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 city_id
        {
            get
            {
                return _city_id;
            }
            set
            {
                if (_city_id != value)
                {
                    Oncity_idChanging(value);
                    ReportPropertyChanging("city_id");
                    _city_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("city_id");
                    Oncity_idChanged();
                }
            }
        }
        private global::System.Int32 _city_id;
        partial void Oncity_idChanging(global::System.Int32 value);
        partial void Oncity_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String city_name
        {
            get
            {
                return _city_name;
            }
            set
            {
                Oncity_nameChanging(value);
                ReportPropertyChanging("city_name");
                _city_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("city_name");
                Oncity_nameChanged();
            }
        }
        private global::System.String _city_name;
        partial void Oncity_nameChanging(global::System.String value);
        partial void Oncity_nameChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ProductListDBModel", Name="Client")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Client : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Client object.
        /// </summary>
        /// <param name="user_id">Initial value of the user_id property.</param>
        public static Client CreateClient(global::System.Int32 user_id)
        {
            Client client = new Client();
            client.user_id = user_id;
            return client;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 user_id
        {
            get
            {
                return _user_id;
            }
            set
            {
                if (_user_id != value)
                {
                    Onuser_idChanging(value);
                    ReportPropertyChanging("user_id");
                    _user_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("user_id");
                    Onuser_idChanged();
                }
            }
        }
        private global::System.Int32 _user_id;
        partial void Onuser_idChanging(global::System.Int32 value);
        partial void Onuser_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String password
        {
            get
            {
                return _password;
            }
            set
            {
                OnpasswordChanging(value);
                ReportPropertyChanging("password");
                _password = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("password");
                OnpasswordChanged();
            }
        }
        private global::System.String _password;
        partial void OnpasswordChanging(global::System.String value);
        partial void OnpasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> join_date
        {
            get
            {
                return _join_date;
            }
            set
            {
                Onjoin_dateChanging(value);
                ReportPropertyChanging("join_date");
                _join_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("join_date");
                Onjoin_dateChanged();
            }
        }
        private Nullable<global::System.DateTime> _join_date;
        partial void Onjoin_dateChanging(Nullable<global::System.DateTime> value);
        partial void Onjoin_dateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> last_login_date
        {
            get
            {
                return _last_login_date;
            }
            set
            {
                Onlast_login_dateChanging(value);
                ReportPropertyChanging("last_login_date");
                _last_login_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("last_login_date");
                Onlast_login_dateChanged();
            }
        }
        private Nullable<global::System.DateTime> _last_login_date;
        partial void Onlast_login_dateChanging(Nullable<global::System.DateTime> value);
        partial void Onlast_login_dateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> city_id
        {
            get
            {
                return _city_id;
            }
            set
            {
                Oncity_idChanging(value);
                ReportPropertyChanging("city_id");
                _city_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("city_id");
                Oncity_idChanged();
            }
        }
        private Nullable<global::System.Int32> _city_id;
        partial void Oncity_idChanging(Nullable<global::System.Int32> value);
        partial void Oncity_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String address
        {
            get
            {
                return _address;
            }
            set
            {
                OnaddressChanging(value);
                ReportPropertyChanging("address");
                _address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("address");
                OnaddressChanged();
            }
        }
        private global::System.String _address;
        partial void OnaddressChanging(global::System.String value);
        partial void OnaddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> update_date_shop_list
        {
            get
            {
                return _update_date_shop_list;
            }
            set
            {
                Onupdate_date_shop_listChanging(value);
                ReportPropertyChanging("update_date_shop_list");
                _update_date_shop_list = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("update_date_shop_list");
                Onupdate_date_shop_listChanged();
            }
        }
        private Nullable<global::System.DateTime> _update_date_shop_list;
        partial void Onupdate_date_shop_listChanging(Nullable<global::System.DateTime> value);
        partial void Onupdate_date_shop_listChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String comments
        {
            get
            {
                return _comments;
            }
            set
            {
                OncommentsChanging(value);
                ReportPropertyChanging("comments");
                _comments = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("comments");
                OncommentsChanged();
            }
        }
        private global::System.String _comments;
        partial void OncommentsChanging(global::System.String value);
        partial void OncommentsChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ProductListDBModel", "FK_Shopping_List_Clients", "Shopping_List")]
        public EntityCollection<Shopping_List> Shopping_List
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Shopping_List>("ProductListDBModel.FK_Shopping_List_Clients", "Shopping_List");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Shopping_List>("ProductListDBModel.FK_Shopping_List_Clients", "Shopping_List", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ProductListDBModel", "FK_Shopping_List_Hist_Clients", "Shopping_List_Hist")]
        public EntityCollection<Shopping_List_Hist> Shopping_List_Hist
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Shopping_List_Hist>("ProductListDBModel.FK_Shopping_List_Hist_Clients", "Shopping_List_Hist");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Shopping_List_Hist>("ProductListDBModel.FK_Shopping_List_Hist_Clients", "Shopping_List_Hist", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ProductListDBModel", "FK_Tips_Clients", "Tip")]
        public EntityCollection<Tip> Tips
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Tip>("ProductListDBModel.FK_Tips_Clients", "Tip");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Tip>("ProductListDBModel.FK_Tips_Clients", "Tip", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ProductListDBModel", Name="Measure")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Measure : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Measure object.
        /// </summary>
        /// <param name="measure_unit_id">Initial value of the measure_unit_id property.</param>
        public static Measure CreateMeasure(global::System.Int32 measure_unit_id)
        {
            Measure measure = new Measure();
            measure.measure_unit_id = measure_unit_id;
            return measure;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 measure_unit_id
        {
            get
            {
                return _measure_unit_id;
            }
            set
            {
                if (_measure_unit_id != value)
                {
                    Onmeasure_unit_idChanging(value);
                    ReportPropertyChanging("measure_unit_id");
                    _measure_unit_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("measure_unit_id");
                    Onmeasure_unit_idChanged();
                }
            }
        }
        private global::System.Int32 _measure_unit_id;
        partial void Onmeasure_unit_idChanging(global::System.Int32 value);
        partial void Onmeasure_unit_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String measure_unit_name
        {
            get
            {
                return _measure_unit_name;
            }
            set
            {
                Onmeasure_unit_nameChanging(value);
                ReportPropertyChanging("measure_unit_name");
                _measure_unit_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("measure_unit_name");
                Onmeasure_unit_nameChanged();
            }
        }
        private global::System.String _measure_unit_name;
        partial void Onmeasure_unit_nameChanging(global::System.String value);
        partial void Onmeasure_unit_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> is_package
        {
            get
            {
                return _is_package;
            }
            set
            {
                Onis_packageChanging(value);
                ReportPropertyChanging("is_package");
                _is_package = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("is_package");
                Onis_packageChanged();
            }
        }
        private Nullable<global::System.Int32> _is_package;
        partial void Onis_packageChanging(Nullable<global::System.Int32> value);
        partial void Onis_packageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> is_measure
        {
            get
            {
                return _is_measure;
            }
            set
            {
                Onis_measureChanging(value);
                ReportPropertyChanging("is_measure");
                _is_measure = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("is_measure");
                Onis_measureChanged();
            }
        }
        private Nullable<global::System.Int32> _is_measure;
        partial void Onis_measureChanging(Nullable<global::System.Int32> value);
        partial void Onis_measureChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> add_num
        {
            get
            {
                return _add_num;
            }
            set
            {
                Onadd_numChanging(value);
                ReportPropertyChanging("add_num");
                _add_num = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("add_num");
                Onadd_numChanged();
            }
        }
        private Nullable<global::System.Double> _add_num;
        partial void Onadd_numChanging(Nullable<global::System.Double> value);
        partial void Onadd_numChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ProductListDBModel", "FK_Products_Measures", "Product")]
        public EntityCollection<Product> Products
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Product>("ProductListDBModel.FK_Products_Measures", "Product");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Product>("ProductListDBModel.FK_Products_Measures", "Product", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ProductListDBModel", Name="Product")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Product : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Product object.
        /// </summary>
        /// <param name="product_id">Initial value of the product_id property.</param>
        public static Product CreateProduct(global::System.Int32 product_id)
        {
            Product product = new Product();
            product.product_id = product_id;
            return product;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 product_id
        {
            get
            {
                return _product_id;
            }
            set
            {
                if (_product_id != value)
                {
                    Onproduct_idChanging(value);
                    ReportPropertyChanging("product_id");
                    _product_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("product_id");
                    Onproduct_idChanged();
                }
            }
        }
        private global::System.Int32 _product_id;
        partial void Onproduct_idChanging(global::System.Int32 value);
        partial void Onproduct_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String product_name
        {
            get
            {
                return _product_name;
            }
            set
            {
                Onproduct_nameChanging(value);
                ReportPropertyChanging("product_name");
                _product_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("product_name");
                Onproduct_nameChanged();
            }
        }
        private global::System.String _product_name;
        partial void Onproduct_nameChanging(global::System.String value);
        partial void Onproduct_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> measure_unit_id
        {
            get
            {
                return _measure_unit_id;
            }
            set
            {
                Onmeasure_unit_idChanging(value);
                ReportPropertyChanging("measure_unit_id");
                _measure_unit_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("measure_unit_id");
                Onmeasure_unit_idChanged();
            }
        }
        private Nullable<global::System.Int32> _measure_unit_id;
        partial void Onmeasure_unit_idChanging(Nullable<global::System.Int32> value);
        partial void Onmeasure_unit_idChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ProductListDBModel", "FK_Products_Measures", "Measure")]
        public Measure Measure
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Measure>("ProductListDBModel.FK_Products_Measures", "Measure").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Measure>("ProductListDBModel.FK_Products_Measures", "Measure").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Measure> MeasureReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Measure>("ProductListDBModel.FK_Products_Measures", "Measure");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Measure>("ProductListDBModel.FK_Products_Measures", "Measure", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ProductListDBModel", "FK_Shopping_List_Products", "Shopping_List")]
        public EntityCollection<Shopping_List> Shopping_List
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Shopping_List>("ProductListDBModel.FK_Shopping_List_Products", "Shopping_List");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Shopping_List>("ProductListDBModel.FK_Shopping_List_Products", "Shopping_List", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ProductListDBModel", "FK_Shopping_List_Hist_Products", "Shopping_List_Hist")]
        public EntityCollection<Shopping_List_Hist> Shopping_List_Hist
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Shopping_List_Hist>("ProductListDBModel.FK_Shopping_List_Hist_Products", "Shopping_List_Hist");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Shopping_List_Hist>("ProductListDBModel.FK_Shopping_List_Hist_Products", "Shopping_List_Hist", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ProductListDBModel", "Product_in_storeProduct", "Product_in_store")]
        public EntityCollection<Product_in_store> Product_in_store
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Product_in_store>("ProductListDBModel.Product_in_storeProduct", "Product_in_store");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Product_in_store>("ProductListDBModel.Product_in_storeProduct", "Product_in_store", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ProductListDBModel", Name="Product_in_store")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Product_in_store : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Product_in_store object.
        /// </summary>
        /// <param name="product_in_store_id">Initial value of the product_in_store_id property.</param>
        public static Product_in_store CreateProduct_in_store(global::System.Int32 product_in_store_id)
        {
            Product_in_store product_in_store = new Product_in_store();
            product_in_store.product_in_store_id = product_in_store_id;
            return product_in_store;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 product_in_store_id
        {
            get
            {
                return _product_in_store_id;
            }
            set
            {
                if (_product_in_store_id != value)
                {
                    Onproduct_in_store_idChanging(value);
                    ReportPropertyChanging("product_in_store_id");
                    _product_in_store_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("product_in_store_id");
                    Onproduct_in_store_idChanged();
                }
            }
        }
        private global::System.Int32 _product_in_store_id;
        partial void Onproduct_in_store_idChanging(global::System.Int32 value);
        partial void Onproduct_in_store_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> product_id
        {
            get
            {
                return _product_id;
            }
            set
            {
                Onproduct_idChanging(value);
                ReportPropertyChanging("product_id");
                _product_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("product_id");
                Onproduct_idChanged();
            }
        }
        private Nullable<global::System.Int32> _product_id;
        partial void Onproduct_idChanging(Nullable<global::System.Int32> value);
        partial void Onproduct_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> store_id
        {
            get
            {
                return _store_id;
            }
            set
            {
                Onstore_idChanging(value);
                ReportPropertyChanging("store_id");
                _store_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("store_id");
                Onstore_idChanged();
            }
        }
        private Nullable<global::System.Int32> _store_id;
        partial void Onstore_idChanging(Nullable<global::System.Int32> value);
        partial void Onstore_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> price
        {
            get
            {
                return _price;
            }
            set
            {
                OnpriceChanging(value);
                ReportPropertyChanging("price");
                _price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("price");
                OnpriceChanged();
            }
        }
        private Nullable<global::System.Decimal> _price;
        partial void OnpriceChanging(Nullable<global::System.Decimal> value);
        partial void OnpriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> price_date
        {
            get
            {
                return _price_date;
            }
            set
            {
                Onprice_dateChanging(value);
                ReportPropertyChanging("price_date");
                _price_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("price_date");
                Onprice_dateChanged();
            }
        }
        private Nullable<global::System.DateTime> _price_date;
        partial void Onprice_dateChanging(Nullable<global::System.DateTime> value);
        partial void Onprice_dateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> updated_by_user_id
        {
            get
            {
                return _updated_by_user_id;
            }
            set
            {
                Onupdated_by_user_idChanging(value);
                ReportPropertyChanging("updated_by_user_id");
                _updated_by_user_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("updated_by_user_id");
                Onupdated_by_user_idChanged();
            }
        }
        private Nullable<global::System.Int32> _updated_by_user_id;
        partial void Onupdated_by_user_idChanging(Nullable<global::System.Int32> value);
        partial void Onupdated_by_user_idChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ProductListDBModel", "Product_in_storeProduct", "Product")]
        public Product Product
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("ProductListDBModel.Product_in_storeProduct", "Product").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("ProductListDBModel.Product_in_storeProduct", "Product").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Product> ProductReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("ProductListDBModel.Product_in_storeProduct", "Product");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Product>("ProductListDBModel.Product_in_storeProduct", "Product", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ProductListDBModel", Name="Sector")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Sector : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Sector object.
        /// </summary>
        /// <param name="sector_id">Initial value of the sector_id property.</param>
        /// <param name="city_id">Initial value of the city_id property.</param>
        public static Sector CreateSector(global::System.Int32 sector_id, global::System.Int32 city_id)
        {
            Sector sector = new Sector();
            sector.sector_id = sector_id;
            sector.city_id = city_id;
            return sector;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 sector_id
        {
            get
            {
                return _sector_id;
            }
            set
            {
                if (_sector_id != value)
                {
                    Onsector_idChanging(value);
                    ReportPropertyChanging("sector_id");
                    _sector_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("sector_id");
                    Onsector_idChanged();
                }
            }
        }
        private global::System.Int32 _sector_id;
        partial void Onsector_idChanging(global::System.Int32 value);
        partial void Onsector_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String sector_name
        {
            get
            {
                return _sector_name;
            }
            set
            {
                Onsector_nameChanging(value);
                ReportPropertyChanging("sector_name");
                _sector_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("sector_name");
                Onsector_nameChanged();
            }
        }
        private global::System.String _sector_name;
        partial void Onsector_nameChanging(global::System.String value);
        partial void Onsector_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 city_id
        {
            get
            {
                return _city_id;
            }
            set
            {
                Oncity_idChanging(value);
                ReportPropertyChanging("city_id");
                _city_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("city_id");
                Oncity_idChanged();
            }
        }
        private global::System.Int32 _city_id;
        partial void Oncity_idChanging(global::System.Int32 value);
        partial void Oncity_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String city_name
        {
            get
            {
                return _city_name;
            }
            set
            {
                Oncity_nameChanging(value);
                ReportPropertyChanging("city_name");
                _city_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("city_name");
                Oncity_nameChanged();
            }
        }
        private global::System.String _city_name;
        partial void Oncity_nameChanging(global::System.String value);
        partial void Oncity_nameChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ProductListDBModel", Name="Shopping_List")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Shopping_List : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Shopping_List object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static Shopping_List CreateShopping_List(global::System.Int32 id)
        {
            Shopping_List shopping_List = new Shopping_List();
            shopping_List.id = id;
            return shopping_List;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> user_id
        {
            get
            {
                return _user_id;
            }
            set
            {
                Onuser_idChanging(value);
                ReportPropertyChanging("user_id");
                _user_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("user_id");
                Onuser_idChanged();
            }
        }
        private Nullable<global::System.Int32> _user_id;
        partial void Onuser_idChanging(Nullable<global::System.Int32> value);
        partial void Onuser_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> product_id
        {
            get
            {
                return _product_id;
            }
            set
            {
                Onproduct_idChanging(value);
                ReportPropertyChanging("product_id");
                _product_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("product_id");
                Onproduct_idChanged();
            }
        }
        private Nullable<global::System.Int32> _product_id;
        partial void Onproduct_idChanging(Nullable<global::System.Int32> value);
        partial void Onproduct_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> qtty
        {
            get
            {
                return _qtty;
            }
            set
            {
                OnqttyChanging(value);
                ReportPropertyChanging("qtty");
                _qtty = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("qtty");
                OnqttyChanged();
            }
        }
        private Nullable<global::System.Double> _qtty;
        partial void OnqttyChanging(Nullable<global::System.Double> value);
        partial void OnqttyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> order_no
        {
            get
            {
                return _order_no;
            }
            set
            {
                Onorder_noChanging(value);
                ReportPropertyChanging("order_no");
                _order_no = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("order_no");
                Onorder_noChanged();
            }
        }
        private Nullable<global::System.Int32> _order_no;
        partial void Onorder_noChanging(Nullable<global::System.Int32> value);
        partial void Onorder_noChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String free_text
        {
            get
            {
                return _free_text;
            }
            set
            {
                Onfree_textChanging(value);
                ReportPropertyChanging("free_text");
                _free_text = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("free_text");
                Onfree_textChanged();
            }
        }
        private global::System.String _free_text;
        partial void Onfree_textChanging(global::System.String value);
        partial void Onfree_textChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ProductListDBModel", "FK_Shopping_List_Clients", "Client")]
        public Client Client
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Client>("ProductListDBModel.FK_Shopping_List_Clients", "Client").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Client>("ProductListDBModel.FK_Shopping_List_Clients", "Client").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Client> ClientReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Client>("ProductListDBModel.FK_Shopping_List_Clients", "Client");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Client>("ProductListDBModel.FK_Shopping_List_Clients", "Client", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ProductListDBModel", "FK_Shopping_List_Products", "Product")]
        public Product Product
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("ProductListDBModel.FK_Shopping_List_Products", "Product").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("ProductListDBModel.FK_Shopping_List_Products", "Product").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Product> ProductReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("ProductListDBModel.FK_Shopping_List_Products", "Product");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Product>("ProductListDBModel.FK_Shopping_List_Products", "Product", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ProductListDBModel", Name="Shopping_List_Hist")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Shopping_List_Hist : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Shopping_List_Hist object.
        /// </summary>
        /// <param name="shopping_list_hist_id">Initial value of the shopping_list_hist_id property.</param>
        /// <param name="user_id">Initial value of the user_id property.</param>
        /// <param name="product_id">Initial value of the product_id property.</param>
        public static Shopping_List_Hist CreateShopping_List_Hist(global::System.Int32 shopping_list_hist_id, global::System.Int32 user_id, global::System.Int32 product_id)
        {
            Shopping_List_Hist shopping_List_Hist = new Shopping_List_Hist();
            shopping_List_Hist.shopping_list_hist_id = shopping_list_hist_id;
            shopping_List_Hist.user_id = user_id;
            shopping_List_Hist.product_id = product_id;
            return shopping_List_Hist;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 shopping_list_hist_id
        {
            get
            {
                return _shopping_list_hist_id;
            }
            set
            {
                if (_shopping_list_hist_id != value)
                {
                    Onshopping_list_hist_idChanging(value);
                    ReportPropertyChanging("shopping_list_hist_id");
                    _shopping_list_hist_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("shopping_list_hist_id");
                    Onshopping_list_hist_idChanged();
                }
            }
        }
        private global::System.Int32 _shopping_list_hist_id;
        partial void Onshopping_list_hist_idChanging(global::System.Int32 value);
        partial void Onshopping_list_hist_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 user_id
        {
            get
            {
                return _user_id;
            }
            set
            {
                Onuser_idChanging(value);
                ReportPropertyChanging("user_id");
                _user_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("user_id");
                Onuser_idChanged();
            }
        }
        private global::System.Int32 _user_id;
        partial void Onuser_idChanging(global::System.Int32 value);
        partial void Onuser_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 product_id
        {
            get
            {
                return _product_id;
            }
            set
            {
                Onproduct_idChanging(value);
                ReportPropertyChanging("product_id");
                _product_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("product_id");
                Onproduct_idChanged();
            }
        }
        private global::System.Int32 _product_id;
        partial void Onproduct_idChanging(global::System.Int32 value);
        partial void Onproduct_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> qtty
        {
            get
            {
                return _qtty;
            }
            set
            {
                OnqttyChanging(value);
                ReportPropertyChanging("qtty");
                _qtty = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("qtty");
                OnqttyChanged();
            }
        }
        private Nullable<global::System.Double> _qtty;
        partial void OnqttyChanging(Nullable<global::System.Double> value);
        partial void OnqttyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String stored_list_name
        {
            get
            {
                return _stored_list_name;
            }
            set
            {
                Onstored_list_nameChanging(value);
                ReportPropertyChanging("stored_list_name");
                _stored_list_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("stored_list_name");
                Onstored_list_nameChanged();
            }
        }
        private global::System.String _stored_list_name;
        partial void Onstored_list_nameChanging(global::System.String value);
        partial void Onstored_list_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> save_date
        {
            get
            {
                return _save_date;
            }
            set
            {
                Onsave_dateChanging(value);
                ReportPropertyChanging("save_date");
                _save_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("save_date");
                Onsave_dateChanged();
            }
        }
        private Nullable<global::System.DateTime> _save_date;
        partial void Onsave_dateChanging(Nullable<global::System.DateTime> value);
        partial void Onsave_dateChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ProductListDBModel", "FK_Shopping_List_Hist_Clients", "Client")]
        public Client Client
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Client>("ProductListDBModel.FK_Shopping_List_Hist_Clients", "Client").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Client>("ProductListDBModel.FK_Shopping_List_Hist_Clients", "Client").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Client> ClientReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Client>("ProductListDBModel.FK_Shopping_List_Hist_Clients", "Client");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Client>("ProductListDBModel.FK_Shopping_List_Hist_Clients", "Client", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ProductListDBModel", "FK_Shopping_List_Hist_Products", "Product")]
        public Product Product
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("ProductListDBModel.FK_Shopping_List_Hist_Products", "Product").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("ProductListDBModel.FK_Shopping_List_Hist_Products", "Product").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Product> ProductReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("ProductListDBModel.FK_Shopping_List_Hist_Products", "Product");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Product>("ProductListDBModel.FK_Shopping_List_Hist_Products", "Product", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ProductListDBModel", Name="Store")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Store : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Store object.
        /// </summary>
        /// <param name="store_id">Initial value of the store_id property.</param>
        public static Store CreateStore(global::System.Int32 store_id)
        {
            Store store = new Store();
            store.store_id = store_id;
            return store;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 store_id
        {
            get
            {
                return _store_id;
            }
            set
            {
                if (_store_id != value)
                {
                    Onstore_idChanging(value);
                    ReportPropertyChanging("store_id");
                    _store_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("store_id");
                    Onstore_idChanged();
                }
            }
        }
        private global::System.Int32 _store_id;
        partial void Onstore_idChanging(global::System.Int32 value);
        partial void Onstore_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String store_name
        {
            get
            {
                return _store_name;
            }
            set
            {
                Onstore_nameChanging(value);
                ReportPropertyChanging("store_name");
                _store_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("store_name");
                Onstore_nameChanged();
            }
        }
        private global::System.String _store_name;
        partial void Onstore_nameChanging(global::System.String value);
        partial void Onstore_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> store_chain_id
        {
            get
            {
                return _store_chain_id;
            }
            set
            {
                Onstore_chain_idChanging(value);
                ReportPropertyChanging("store_chain_id");
                _store_chain_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("store_chain_id");
                Onstore_chain_idChanged();
            }
        }
        private Nullable<global::System.Int32> _store_chain_id;
        partial void Onstore_chain_idChanging(Nullable<global::System.Int32> value);
        partial void Onstore_chain_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> city_id
        {
            get
            {
                return _city_id;
            }
            set
            {
                Oncity_idChanging(value);
                ReportPropertyChanging("city_id");
                _city_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("city_id");
                Oncity_idChanged();
            }
        }
        private Nullable<global::System.Int32> _city_id;
        partial void Oncity_idChanging(Nullable<global::System.Int32> value);
        partial void Oncity_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String street
        {
            get
            {
                return _street;
            }
            set
            {
                OnstreetChanging(value);
                ReportPropertyChanging("street");
                _street = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("street");
                OnstreetChanged();
            }
        }
        private global::System.String _street;
        partial void OnstreetChanging(global::System.String value);
        partial void OnstreetChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> number
        {
            get
            {
                return _number;
            }
            set
            {
                OnnumberChanging(value);
                ReportPropertyChanging("number");
                _number = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("number");
                OnnumberChanged();
            }
        }
        private Nullable<global::System.Int32> _number;
        partial void OnnumberChanging(Nullable<global::System.Int32> value);
        partial void OnnumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> sector_id
        {
            get
            {
                return _sector_id;
            }
            set
            {
                Onsector_idChanging(value);
                ReportPropertyChanging("sector_id");
                _sector_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("sector_id");
                Onsector_idChanged();
            }
        }
        private Nullable<global::System.Int32> _sector_id;
        partial void Onsector_idChanging(Nullable<global::System.Int32> value);
        partial void Onsector_idChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ProductListDBModel", Name="sysdiagram")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagram : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagram object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagram Createsysdiagram(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagram sysdiagram = new sysdiagram();
            sysdiagram.name = name;
            sysdiagram.principal_id = principal_id;
            sysdiagram.diagram_id = diagram_id;
            return sysdiagram;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ProductListDBModel", Name="Tip")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Tip : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Tip object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static Tip CreateTip(global::System.Int32 id)
        {
            Tip tip = new Tip();
            tip.id = id;
            return tip;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String tip_content
        {
            get
            {
                return _tip_content;
            }
            set
            {
                Ontip_contentChanging(value);
                ReportPropertyChanging("tip_content");
                _tip_content = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("tip_content");
                Ontip_contentChanged();
            }
        }
        private global::System.String _tip_content;
        partial void Ontip_contentChanging(global::System.String value);
        partial void Ontip_contentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> tip_enter_date
        {
            get
            {
                return _tip_enter_date;
            }
            set
            {
                Ontip_enter_dateChanging(value);
                ReportPropertyChanging("tip_enter_date");
                _tip_enter_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("tip_enter_date");
                Ontip_enter_dateChanged();
            }
        }
        private Nullable<global::System.DateTime> _tip_enter_date;
        partial void Ontip_enter_dateChanging(Nullable<global::System.DateTime> value);
        partial void Ontip_enter_dateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> is_active
        {
            get
            {
                return _is_active;
            }
            set
            {
                Onis_activeChanging(value);
                ReportPropertyChanging("is_active");
                _is_active = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("is_active");
                Onis_activeChanged();
            }
        }
        private Nullable<global::System.Int32> _is_active;
        partial void Onis_activeChanging(Nullable<global::System.Int32> value);
        partial void Onis_activeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> user_id
        {
            get
            {
                return _user_id;
            }
            set
            {
                Onuser_idChanging(value);
                ReportPropertyChanging("user_id");
                _user_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("user_id");
                Onuser_idChanged();
            }
        }
        private Nullable<global::System.Int32> _user_id;
        partial void Onuser_idChanging(Nullable<global::System.Int32> value);
        partial void Onuser_idChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ProductListDBModel", "FK_Tips_Clients", "Client")]
        public Client Client
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Client>("ProductListDBModel.FK_Tips_Clients", "Client").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Client>("ProductListDBModel.FK_Tips_Clients", "Client").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Client> ClientReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Client>("ProductListDBModel.FK_Tips_Clients", "Client");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Client>("ProductListDBModel.FK_Tips_Clients", "Client", value);
                }
            }
        }

        #endregion

    }

    #endregion

    #region ComplexTypes
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="ProductListDBModel", Name="Shopping_list_proc_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class Shopping_list_proc_Result : ComplexObject
    {
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> product_list_line
        {
            get
            {
                return _product_list_line;
            }
            set
            {
                Onproduct_list_lineChanging(value);
                ReportPropertyChanging("product_list_line");
                _product_list_line = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("product_list_line");
                Onproduct_list_lineChanged();
            }
        }
        private Nullable<global::System.Double> _product_list_line;
        partial void Onproduct_list_lineChanging(Nullable<global::System.Double> value);
        partial void Onproduct_list_lineChanged();

        #endregion

    }

    #endregion

    
}
