//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("ProductListDBModel", "FK_Products_Measures", "Measure", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(ProductListDBModel.Measure), "Product", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ProductListDBModel.Product), true)]
[assembly: EdmRelationshipAttribute("ProductListDBModel", "FK_Shopping_List_Clients", "Client", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(ProductListDBModel.Client), "Shopping_List", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ProductListDBModel.Shopping_List), true)]
[assembly: EdmRelationshipAttribute("ProductListDBModel", "FK_Shopping_List_Products", "Product", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(ProductListDBModel.Product), "Shopping_List", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ProductListDBModel.Shopping_List), true)]
[assembly: EdmRelationshipAttribute("ProductListDBModel", "FK_Shopping_List_Hist_Clients", "Client", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ProductListDBModel.Client), "Shopping_List_Hist", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ProductListDBModel.Shopping_List_Hist), true)]
[assembly: EdmRelationshipAttribute("ProductListDBModel", "FK_Shopping_List_Hist_Products", "Product", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ProductListDBModel.Product), "Shopping_List_Hist", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ProductListDBModel.Shopping_List_Hist), true)]
[assembly: EdmRelationshipAttribute("ProductListDBModel", "FK_Tips_Clients", "Client", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(ProductListDBModel.Client), "Tip", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ProductListDBModel.Tip), true)]

#endregion

namespace ProductListDBModel
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ProdListDBEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ProdListDBEntities object using the connection string found in the 'ProdListDBEntities' section of the application configuration file.
        /// </summary>
        public ProdListDBEntities() : base("name=ProdListDBEntities", "ProdListDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ProdListDBEntities object.
        /// </summary>
        public ProdListDBEntities(string connectionString) : base(connectionString, "ProdListDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ProdListDBEntities object.
        /// </summary>
        public ProdListDBEntities(EntityConnection connection) : base(connection, "ProdListDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<City> Cities
        {
            get
            {
                if ((_Cities == null))
                {
                    _Cities = base.CreateObjectSet<City>("Cities");
                }
                return _Cities;
            }
        }
        private ObjectSet<City> _Cities;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Client> Clients
        {
            get
            {
                if ((_Clients == null))
                {
                    _Clients = base.CreateObjectSet<Client>("Clients");
                }
                return _Clients;
            }
        }
        private ObjectSet<Client> _Clients;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Measure> Measures
        {
            get
            {
                if ((_Measures == null))
                {
                    _Measures = base.CreateObjectSet<Measure>("Measures");
                }
                return _Measures;
            }
        }
        private ObjectSet<Measure> _Measures;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Product> Products
        {
            get
            {
                if ((_Products == null))
                {
                    _Products = base.CreateObjectSet<Product>("Products");
                }
                return _Products;
            }
        }
        private ObjectSet<Product> _Products;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Shopping_List> Shopping_List
        {
            get
            {
                if ((_Shopping_List == null))
                {
                    _Shopping_List = base.CreateObjectSet<Shopping_List>("Shopping_List");
                }
                return _Shopping_List;
            }
        }
        private ObjectSet<Shopping_List> _Shopping_List;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Shopping_List_Hist> Shopping_List_Hist
        {
            get
            {
                if ((_Shopping_List_Hist == null))
                {
                    _Shopping_List_Hist = base.CreateObjectSet<Shopping_List_Hist>("Shopping_List_Hist");
                }
                return _Shopping_List_Hist;
            }
        }
        private ObjectSet<Shopping_List_Hist> _Shopping_List_Hist;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Tip> Tips
        {
            get
            {
                if ((_Tips == null))
                {
                    _Tips = base.CreateObjectSet<Tip>("Tips");
                }
                return _Tips;
            }
        }
        private ObjectSet<Tip> _Tips;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Cities EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCities(City city)
        {
            base.AddObject("Cities", city);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Clients EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToClients(Client client)
        {
            base.AddObject("Clients", client);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Measures EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMeasures(Measure measure)
        {
            base.AddObject("Measures", measure);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Products EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProducts(Product product)
        {
            base.AddObject("Products", product);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Shopping_List EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToShopping_List(Shopping_List shopping_List)
        {
            base.AddObject("Shopping_List", shopping_List);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Shopping_List_Hist EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToShopping_List_Hist(Shopping_List_Hist shopping_List_Hist)
        {
            base.AddObject("Shopping_List_Hist", shopping_List_Hist);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Tips EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTips(Tip tip)
        {
            base.AddObject("Tips", tip);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ProductListDBModel", Name="City")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class City : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new City object.
        /// </summary>
        /// <param name="city_id">Initial value of the city_id property.</param>
        public static City CreateCity(global::System.Int32 city_id)
        {
            City city = new City();
            city.city_id = city_id;
            return city;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 city_id
        {
            get
            {
                return _city_id;
            }
            set
            {
                if (_city_id != value)
                {
                    Oncity_idChanging(value);
                    ReportPropertyChanging("city_id");
                    _city_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("city_id");
                    Oncity_idChanged();
                }
            }
        }
        private global::System.Int32 _city_id;
        partial void Oncity_idChanging(global::System.Int32 value);
        partial void Oncity_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String city_name
        {
            get
            {
                return _city_name;
            }
            set
            {
                Oncity_nameChanging(value);
                ReportPropertyChanging("city_name");
                _city_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("city_name");
                Oncity_nameChanged();
            }
        }
        private global::System.String _city_name;
        partial void Oncity_nameChanging(global::System.String value);
        partial void Oncity_nameChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ProductListDBModel", Name="Client")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Client : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Client object.
        /// </summary>
        /// <param name="user_id">Initial value of the user_id property.</param>
        public static Client CreateClient(global::System.Int32 user_id)
        {
            Client client = new Client();
            client.user_id = user_id;
            return client;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 user_id
        {
            get
            {
                return _user_id;
            }
            set
            {
                if (_user_id != value)
                {
                    Onuser_idChanging(value);
                    ReportPropertyChanging("user_id");
                    _user_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("user_id");
                    Onuser_idChanged();
                }
            }
        }
        private global::System.Int32 _user_id;
        partial void Onuser_idChanging(global::System.Int32 value);
        partial void Onuser_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String password
        {
            get
            {
                return _password;
            }
            set
            {
                OnpasswordChanging(value);
                ReportPropertyChanging("password");
                _password = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("password");
                OnpasswordChanged();
            }
        }
        private global::System.String _password;
        partial void OnpasswordChanging(global::System.String value);
        partial void OnpasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> join_date
        {
            get
            {
                return _join_date;
            }
            set
            {
                Onjoin_dateChanging(value);
                ReportPropertyChanging("join_date");
                _join_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("join_date");
                Onjoin_dateChanged();
            }
        }
        private Nullable<global::System.DateTime> _join_date;
        partial void Onjoin_dateChanging(Nullable<global::System.DateTime> value);
        partial void Onjoin_dateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> last_login_date
        {
            get
            {
                return _last_login_date;
            }
            set
            {
                Onlast_login_dateChanging(value);
                ReportPropertyChanging("last_login_date");
                _last_login_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("last_login_date");
                Onlast_login_dateChanged();
            }
        }
        private Nullable<global::System.DateTime> _last_login_date;
        partial void Onlast_login_dateChanging(Nullable<global::System.DateTime> value);
        partial void Onlast_login_dateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> city_id
        {
            get
            {
                return _city_id;
            }
            set
            {
                Oncity_idChanging(value);
                ReportPropertyChanging("city_id");
                _city_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("city_id");
                Oncity_idChanged();
            }
        }
        private Nullable<global::System.Int32> _city_id;
        partial void Oncity_idChanging(Nullable<global::System.Int32> value);
        partial void Oncity_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String address
        {
            get
            {
                return _address;
            }
            set
            {
                OnaddressChanging(value);
                ReportPropertyChanging("address");
                _address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("address");
                OnaddressChanged();
            }
        }
        private global::System.String _address;
        partial void OnaddressChanging(global::System.String value);
        partial void OnaddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> update_date_shop_list
        {
            get
            {
                return _update_date_shop_list;
            }
            set
            {
                Onupdate_date_shop_listChanging(value);
                ReportPropertyChanging("update_date_shop_list");
                _update_date_shop_list = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("update_date_shop_list");
                Onupdate_date_shop_listChanged();
            }
        }
        private Nullable<global::System.DateTime> _update_date_shop_list;
        partial void Onupdate_date_shop_listChanging(Nullable<global::System.DateTime> value);
        partial void Onupdate_date_shop_listChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String comments
        {
            get
            {
                return _comments;
            }
            set
            {
                OncommentsChanging(value);
                ReportPropertyChanging("comments");
                _comments = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("comments");
                OncommentsChanged();
            }
        }
        private global::System.String _comments;
        partial void OncommentsChanging(global::System.String value);
        partial void OncommentsChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ProductListDBModel", "FK_Shopping_List_Clients", "Shopping_List")]
        public EntityCollection<Shopping_List> Shopping_List
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Shopping_List>("ProductListDBModel.FK_Shopping_List_Clients", "Shopping_List");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Shopping_List>("ProductListDBModel.FK_Shopping_List_Clients", "Shopping_List", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ProductListDBModel", "FK_Shopping_List_Hist_Clients", "Shopping_List_Hist")]
        public EntityCollection<Shopping_List_Hist> Shopping_List_Hist
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Shopping_List_Hist>("ProductListDBModel.FK_Shopping_List_Hist_Clients", "Shopping_List_Hist");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Shopping_List_Hist>("ProductListDBModel.FK_Shopping_List_Hist_Clients", "Shopping_List_Hist", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ProductListDBModel", "FK_Tips_Clients", "Tip")]
        public EntityCollection<Tip> Tips
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Tip>("ProductListDBModel.FK_Tips_Clients", "Tip");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Tip>("ProductListDBModel.FK_Tips_Clients", "Tip", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ProductListDBModel", Name="Measure")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Measure : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Measure object.
        /// </summary>
        /// <param name="measure_unit_id">Initial value of the measure_unit_id property.</param>
        public static Measure CreateMeasure(global::System.Int32 measure_unit_id)
        {
            Measure measure = new Measure();
            measure.measure_unit_id = measure_unit_id;
            return measure;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 measure_unit_id
        {
            get
            {
                return _measure_unit_id;
            }
            set
            {
                if (_measure_unit_id != value)
                {
                    Onmeasure_unit_idChanging(value);
                    ReportPropertyChanging("measure_unit_id");
                    _measure_unit_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("measure_unit_id");
                    Onmeasure_unit_idChanged();
                }
            }
        }
        private global::System.Int32 _measure_unit_id;
        partial void Onmeasure_unit_idChanging(global::System.Int32 value);
        partial void Onmeasure_unit_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String measure_unit_name
        {
            get
            {
                return _measure_unit_name;
            }
            set
            {
                Onmeasure_unit_nameChanging(value);
                ReportPropertyChanging("measure_unit_name");
                _measure_unit_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("measure_unit_name");
                Onmeasure_unit_nameChanged();
            }
        }
        private global::System.String _measure_unit_name;
        partial void Onmeasure_unit_nameChanging(global::System.String value);
        partial void Onmeasure_unit_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> is_package
        {
            get
            {
                return _is_package;
            }
            set
            {
                Onis_packageChanging(value);
                ReportPropertyChanging("is_package");
                _is_package = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("is_package");
                Onis_packageChanged();
            }
        }
        private Nullable<global::System.Int32> _is_package;
        partial void Onis_packageChanging(Nullable<global::System.Int32> value);
        partial void Onis_packageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> is_measure
        {
            get
            {
                return _is_measure;
            }
            set
            {
                Onis_measureChanging(value);
                ReportPropertyChanging("is_measure");
                _is_measure = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("is_measure");
                Onis_measureChanged();
            }
        }
        private Nullable<global::System.Int32> _is_measure;
        partial void Onis_measureChanging(Nullable<global::System.Int32> value);
        partial void Onis_measureChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ProductListDBModel", "FK_Products_Measures", "Product")]
        public EntityCollection<Product> Products
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Product>("ProductListDBModel.FK_Products_Measures", "Product");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Product>("ProductListDBModel.FK_Products_Measures", "Product", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ProductListDBModel", Name="Product")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Product : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Product object.
        /// </summary>
        /// <param name="product_id">Initial value of the product_id property.</param>
        public static Product CreateProduct(global::System.Int32 product_id)
        {
            Product product = new Product();
            product.product_id = product_id;
            return product;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 product_id
        {
            get
            {
                return _product_id;
            }
            set
            {
                if (_product_id != value)
                {
                    Onproduct_idChanging(value);
                    ReportPropertyChanging("product_id");
                    _product_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("product_id");
                    Onproduct_idChanged();
                }
            }
        }
        private global::System.Int32 _product_id;
        partial void Onproduct_idChanging(global::System.Int32 value);
        partial void Onproduct_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String product_name
        {
            get
            {
                return _product_name;
            }
            set
            {
                Onproduct_nameChanging(value);
                ReportPropertyChanging("product_name");
                _product_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("product_name");
                Onproduct_nameChanged();
            }
        }
        private global::System.String _product_name;
        partial void Onproduct_nameChanging(global::System.String value);
        partial void Onproduct_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> measure_unit_id
        {
            get
            {
                return _measure_unit_id;
            }
            set
            {
                Onmeasure_unit_idChanging(value);
                ReportPropertyChanging("measure_unit_id");
                _measure_unit_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("measure_unit_id");
                Onmeasure_unit_idChanged();
            }
        }
        private Nullable<global::System.Int32> _measure_unit_id;
        partial void Onmeasure_unit_idChanging(Nullable<global::System.Int32> value);
        partial void Onmeasure_unit_idChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ProductListDBModel", "FK_Products_Measures", "Measure")]
        public Measure Measure
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Measure>("ProductListDBModel.FK_Products_Measures", "Measure").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Measure>("ProductListDBModel.FK_Products_Measures", "Measure").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Measure> MeasureReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Measure>("ProductListDBModel.FK_Products_Measures", "Measure");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Measure>("ProductListDBModel.FK_Products_Measures", "Measure", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ProductListDBModel", "FK_Shopping_List_Products", "Shopping_List")]
        public EntityCollection<Shopping_List> Shopping_List
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Shopping_List>("ProductListDBModel.FK_Shopping_List_Products", "Shopping_List");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Shopping_List>("ProductListDBModel.FK_Shopping_List_Products", "Shopping_List", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ProductListDBModel", "FK_Shopping_List_Hist_Products", "Shopping_List_Hist")]
        public EntityCollection<Shopping_List_Hist> Shopping_List_Hist
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Shopping_List_Hist>("ProductListDBModel.FK_Shopping_List_Hist_Products", "Shopping_List_Hist");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Shopping_List_Hist>("ProductListDBModel.FK_Shopping_List_Hist_Products", "Shopping_List_Hist", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ProductListDBModel", Name="Shopping_List")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Shopping_List : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Shopping_List object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static Shopping_List CreateShopping_List(global::System.Int32 id)
        {
            Shopping_List shopping_List = new Shopping_List();
            shopping_List.id = id;
            return shopping_List;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> user_id
        {
            get
            {
                return _user_id;
            }
            set
            {
                Onuser_idChanging(value);
                ReportPropertyChanging("user_id");
                _user_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("user_id");
                Onuser_idChanged();
            }
        }
        private Nullable<global::System.Int32> _user_id;
        partial void Onuser_idChanging(Nullable<global::System.Int32> value);
        partial void Onuser_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> product_id
        {
            get
            {
                return _product_id;
            }
            set
            {
                Onproduct_idChanging(value);
                ReportPropertyChanging("product_id");
                _product_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("product_id");
                Onproduct_idChanged();
            }
        }
        private Nullable<global::System.Int32> _product_id;
        partial void Onproduct_idChanging(Nullable<global::System.Int32> value);
        partial void Onproduct_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> qtty
        {
            get
            {
                return _qtty;
            }
            set
            {
                OnqttyChanging(value);
                ReportPropertyChanging("qtty");
                _qtty = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("qtty");
                OnqttyChanged();
            }
        }
        private Nullable<global::System.Double> _qtty;
        partial void OnqttyChanging(Nullable<global::System.Double> value);
        partial void OnqttyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> order_no
        {
            get
            {
                return _order_no;
            }
            set
            {
                Onorder_noChanging(value);
                ReportPropertyChanging("order_no");
                _order_no = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("order_no");
                Onorder_noChanged();
            }
        }
        private Nullable<global::System.Int32> _order_no;
        partial void Onorder_noChanging(Nullable<global::System.Int32> value);
        partial void Onorder_noChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ProductListDBModel", "FK_Shopping_List_Clients", "Client")]
        public Client Client
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Client>("ProductListDBModel.FK_Shopping_List_Clients", "Client").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Client>("ProductListDBModel.FK_Shopping_List_Clients", "Client").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Client> ClientReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Client>("ProductListDBModel.FK_Shopping_List_Clients", "Client");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Client>("ProductListDBModel.FK_Shopping_List_Clients", "Client", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ProductListDBModel", "FK_Shopping_List_Products", "Product")]
        public Product Product
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("ProductListDBModel.FK_Shopping_List_Products", "Product").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("ProductListDBModel.FK_Shopping_List_Products", "Product").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Product> ProductReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("ProductListDBModel.FK_Shopping_List_Products", "Product");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Product>("ProductListDBModel.FK_Shopping_List_Products", "Product", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ProductListDBModel", Name="Shopping_List_Hist")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Shopping_List_Hist : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Shopping_List_Hist object.
        /// </summary>
        /// <param name="shopping_list_hist_id">Initial value of the shopping_list_hist_id property.</param>
        /// <param name="user_id">Initial value of the user_id property.</param>
        /// <param name="product_id">Initial value of the product_id property.</param>
        public static Shopping_List_Hist CreateShopping_List_Hist(global::System.Int32 shopping_list_hist_id, global::System.Int32 user_id, global::System.Int32 product_id)
        {
            Shopping_List_Hist shopping_List_Hist = new Shopping_List_Hist();
            shopping_List_Hist.shopping_list_hist_id = shopping_list_hist_id;
            shopping_List_Hist.user_id = user_id;
            shopping_List_Hist.product_id = product_id;
            return shopping_List_Hist;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 shopping_list_hist_id
        {
            get
            {
                return _shopping_list_hist_id;
            }
            set
            {
                if (_shopping_list_hist_id != value)
                {
                    Onshopping_list_hist_idChanging(value);
                    ReportPropertyChanging("shopping_list_hist_id");
                    _shopping_list_hist_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("shopping_list_hist_id");
                    Onshopping_list_hist_idChanged();
                }
            }
        }
        private global::System.Int32 _shopping_list_hist_id;
        partial void Onshopping_list_hist_idChanging(global::System.Int32 value);
        partial void Onshopping_list_hist_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 user_id
        {
            get
            {
                return _user_id;
            }
            set
            {
                Onuser_idChanging(value);
                ReportPropertyChanging("user_id");
                _user_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("user_id");
                Onuser_idChanged();
            }
        }
        private global::System.Int32 _user_id;
        partial void Onuser_idChanging(global::System.Int32 value);
        partial void Onuser_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 product_id
        {
            get
            {
                return _product_id;
            }
            set
            {
                Onproduct_idChanging(value);
                ReportPropertyChanging("product_id");
                _product_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("product_id");
                Onproduct_idChanged();
            }
        }
        private global::System.Int32 _product_id;
        partial void Onproduct_idChanging(global::System.Int32 value);
        partial void Onproduct_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> qtty
        {
            get
            {
                return _qtty;
            }
            set
            {
                OnqttyChanging(value);
                ReportPropertyChanging("qtty");
                _qtty = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("qtty");
                OnqttyChanged();
            }
        }
        private Nullable<global::System.Double> _qtty;
        partial void OnqttyChanging(Nullable<global::System.Double> value);
        partial void OnqttyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String stored_list_name
        {
            get
            {
                return _stored_list_name;
            }
            set
            {
                Onstored_list_nameChanging(value);
                ReportPropertyChanging("stored_list_name");
                _stored_list_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("stored_list_name");
                Onstored_list_nameChanged();
            }
        }
        private global::System.String _stored_list_name;
        partial void Onstored_list_nameChanging(global::System.String value);
        partial void Onstored_list_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> save_date
        {
            get
            {
                return _save_date;
            }
            set
            {
                Onsave_dateChanging(value);
                ReportPropertyChanging("save_date");
                _save_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("save_date");
                Onsave_dateChanged();
            }
        }
        private Nullable<global::System.DateTime> _save_date;
        partial void Onsave_dateChanging(Nullable<global::System.DateTime> value);
        partial void Onsave_dateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ProductListDBModel", "FK_Shopping_List_Hist_Clients", "Client")]
        public Client Client
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Client>("ProductListDBModel.FK_Shopping_List_Hist_Clients", "Client").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Client>("ProductListDBModel.FK_Shopping_List_Hist_Clients", "Client").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Client> ClientReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Client>("ProductListDBModel.FK_Shopping_List_Hist_Clients", "Client");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Client>("ProductListDBModel.FK_Shopping_List_Hist_Clients", "Client", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ProductListDBModel", "FK_Shopping_List_Hist_Products", "Product")]
        public Product Product
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("ProductListDBModel.FK_Shopping_List_Hist_Products", "Product").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("ProductListDBModel.FK_Shopping_List_Hist_Products", "Product").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Product> ProductReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("ProductListDBModel.FK_Shopping_List_Hist_Products", "Product");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Product>("ProductListDBModel.FK_Shopping_List_Hist_Products", "Product", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ProductListDBModel", Name="Tip")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Tip : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Tip object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static Tip CreateTip(global::System.Int32 id)
        {
            Tip tip = new Tip();
            tip.id = id;
            return tip;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String tip_content
        {
            get
            {
                return _tip_content;
            }
            set
            {
                Ontip_contentChanging(value);
                ReportPropertyChanging("tip_content");
                _tip_content = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("tip_content");
                Ontip_contentChanged();
            }
        }
        private global::System.String _tip_content;
        partial void Ontip_contentChanging(global::System.String value);
        partial void Ontip_contentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> tip_enter_date
        {
            get
            {
                return _tip_enter_date;
            }
            set
            {
                Ontip_enter_dateChanging(value);
                ReportPropertyChanging("tip_enter_date");
                _tip_enter_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("tip_enter_date");
                Ontip_enter_dateChanged();
            }
        }
        private Nullable<global::System.DateTime> _tip_enter_date;
        partial void Ontip_enter_dateChanging(Nullable<global::System.DateTime> value);
        partial void Ontip_enter_dateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> is_active
        {
            get
            {
                return _is_active;
            }
            set
            {
                Onis_activeChanging(value);
                ReportPropertyChanging("is_active");
                _is_active = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("is_active");
                Onis_activeChanged();
            }
        }
        private Nullable<global::System.Int32> _is_active;
        partial void Onis_activeChanging(Nullable<global::System.Int32> value);
        partial void Onis_activeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> user_id
        {
            get
            {
                return _user_id;
            }
            set
            {
                Onuser_idChanging(value);
                ReportPropertyChanging("user_id");
                _user_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("user_id");
                Onuser_idChanged();
            }
        }
        private Nullable<global::System.Int32> _user_id;
        partial void Onuser_idChanging(Nullable<global::System.Int32> value);
        partial void Onuser_idChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ProductListDBModel", "FK_Tips_Clients", "Client")]
        public Client Client
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Client>("ProductListDBModel.FK_Tips_Clients", "Client").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Client>("ProductListDBModel.FK_Tips_Clients", "Client").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Client> ClientReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Client>("ProductListDBModel.FK_Tips_Clients", "Client");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Client>("ProductListDBModel.FK_Tips_Clients", "Client", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
